Bump Astarte Device SDK to 0.6.0
astarte-platform/astarte-message-hub pull request #168
Opened 2023-09-14 15:11 UTC by harlem88

- Prepare next dev cycle to 0.6.0-dev
- Bump Rust to 1.66.1 version

2023-09-14 15:59 UTC, sorru94 commented on src/data/astarte_handler.rs
> +                println!("incoming: {:?}", astarte_data_event);
This could be a log macro like all the others. At the info level.

2023-09-15 07:28 UTC, joshuachp requested changes

2023-09-15 07:28 UTC, joshuachp commented on src/data/astarte_handler.rs
> +    use astarte_device_sdk::error::Error as AstarteSDKError;
Acronyms in rust have the first letter capitalize, not all of them (eg. Arc, Rc, ...) This could be renamed to SdkError for simplicity.

2023-09-15 07:43 UTC, joshuachp requested changes

2023-09-15 07:43 UTC, joshuachp commented on src/data/astarte_handler.rs
> +                };
Nitpick to simplify the match

```rust
let starte_data = astarte_data.data
    .ok_or_else(|| AstarteMessageHubError::AstarteInvalidData(
        "Invalid Astarte data type".to_string(),
    ))?;
```

2023-09-18 08:00 UTC, joshuachp requested changes

2023-09-18 15:05 UTC, joshuachp approved these changes

2023-09-18 15:29 UTC, sorru94 approved these changes

2023-09-18 15:29 UTC, merged