feat(introspection): implement cache introspection
astarte-platform/astarte-message-hub pull request #239
Opened 2024-04-19 16:33 UTC by joshuachp

Cache the introspection of the nodes when it attaches.

2024-04-22 15:53 UTC, rgallor reviewed
LGTM, just use correct sdk and proto dependencies in Cargo.toml once everything necessary has been merged and fix clippy warnings

2024-04-22 15:54 UTC, rgallor approved these changes

2024-05-13 07:58 UTC, rgallor approved these changes

2024-05-13 09:25 UTC, harlem88 requested changes

2024-05-13 09:25 UTC, harlem88 commented on src/cache.rs
> +}
Add some unit tests on the store.

2024-05-13 10:03 UTC, joshuachp commented on src/cache.rs
> +}
Done

2024-05-13 13:28 UTC, merged