Added publish snapshot action
astarte-platform/astarte-message-hub pull request #281
Opened 2024-09-30 10:14 UTC by lucaato

Tested on my fork and this is the kind of tags that I'm expecting.
![image](https://github.com/user-attachments/assets/3cf8374e-4db9-4eb8-bf0a-6b136c6dffcc)

2024-10-02 07:48 UTC, harlem88 approved these changes

2024-10-04 15:32 UTC, rgallor requested changes

2024-10-04 15:32 UTC, rgallor commented on .github/workflows/dockerhub-publish-release.yaml
> +
I'd remove the empty lines (this and the following)

2025-07-07 08:46 UTC, lucaato commented
Example install instructions and version list can be [viewed on my repo](https://github.com/lucaato/astarte-message-hub/pkgs/container/astarte-message-hub).

2025-07-10 12:26 UTC, joshuachp commented on .github/workflows/ghcr-publish-snapshot.yaml
> +          gh run watch ${{ github.run_id }}
I would always publish the snapshot. The file filter is missing the Cargo.toml for example. I think we can stay on the safer side and always publish the snapshot

2025-07-14 07:32 UTC, sorru94 approved these changes

2025-07-14 09:54 UTC, merged