Bump rust msrv to 1.78
astarte-platform/astarte-message-hub pull request #295
Opened 2024-11-29 09:56 UTC by lucaato

2024-11-29 10:01 UTC, joshuachp requested changes
Clap was pinned to a lower version for the MSRV bound, it can now be updated

2024-11-29 14:18 UTC, joshuachp approved these changes

2024-12-02 13:54 UTC, rgallor approved these changes

2024-12-02 14:21 UTC, joshuachp approved these changes

2024-12-05 14:10 UTC, rgallor commented
Maybe you should also update the `astarte-device-sdk` and `astarte-message-hub-proto` in the Cargo.toml (at the moment you could use the git reference), since they have also been update to 1.78.0 MSRV

2024-12-05 14:38 UTC, lucaato commented
We first need to merge the pr [on the sdk](https://github.com/astarte-platform/astarte-device-sdk-rust/pull/395) to be able to reference the master version of that crate too

2024-12-06 14:38 UTC, harlem88 approved these changes

2024-12-06 14:44 UTC, rgallor requested changes

2024-12-06 14:44 UTC, rgallor commented on Cargo.toml
> +astarte-device-sdk = { git = "https://github.com/astarte-platform/astarte-device-sdk-rust", rev = "e8469c09100be2ad5446a7eb3bee359ee8314182"}
you need to change also the sdk mock with the same info as the astarte-device-sdk

2024-12-06 14:53 UTC, joshuachp approved these changes

2024-12-06 15:07 UTC, merged