Improve documentation
astarte-platform/astarte-message-hub pull request #60
Opened 2023-03-14 17:23 UTC by sorru94

Adds docstrings to most public and private functions.

2023-03-15 17:29 UTC, harlem88 requested changes

2023-03-15 17:29 UTC, harlem88 commented on proto/astarteplatform/msghub/astarte_message.proto
> +    AstarteUnset astarte_unset = 4;   // Null payload.
Choose whether to leave a single space after the semicolon or to line it up with the other comments.

2023-03-15 17:29 UTC, harlem88 commented on proto/astarteplatform/msghub/node.proto
> +  repeated bytes interface_jsons = 2; // Serialized .json interface file as bytes array.
same above.

2023-03-15 17:29 UTC, harlem88 commented on src/data/astarte.rs
> +//! The message hub uses an independent handler to communicate with Astarte.
```suggestion
//! The Astarte message hub uses an independent handler to communicate with Astarte.
```

2023-03-15 17:29 UTC, harlem88 commented on src/data/astarte_provider.rs
> +/// An Astarte SDK based implementation of an Astarte handler.
```suggestion
/// An Astarte Device SDK based implementation of an Astarte handler.
```

2023-03-15 17:29 UTC, harlem88 commented on src/data/astarte_provider.rs
> +/// Uses the Astarte SDK to provide subscribe and publish functionality.
```suggestion
/// Uses the Astarte Device SDK to provide subscribe and publish functionality.
```

2023-03-15 17:29 UTC, harlem88 commented on src/data/astarte_provider.rs
> +    /// Polls the Astarte SDK for received messages. When the received message interface
```suggestion
    /// Polls the Astarte Device SDK for received messages. When the received message interface
```

2023-03-15 17:29 UTC, harlem88 commented on src/data/mock_astarte.rs
> +//! Contains a mock version of the Astarte SDK to be used for unit testing.
```suggestion
//! Contains a mock version of the Astarte Device SDK to be used for unit testing.
```

2023-03-17 09:03 UTC, FrancescoVaiani reviewed
A little note about something I myself found confusing

2023-03-17 09:03 UTC, FrancescoVaiani commented on proto/astarteplatform/msghub/node.proto
> +  repeated bytes interface_jsons = 2; // Serialized .json interface file as bytes array.
```suggestion
  repeated bytes interface_jsons = 2; // Array of byte arrays representing all .json interface files of the node.
```

2023-04-18 14:06 UTC, sorru94 commented
Succeeded by #111.

2023-04-18 14:06 UTC, closed without merging