Implement type conversion for AstarteDataType
astarte-platform/astarte-message-hub pull request #8
Opened 2022-09-13 15:32 UTC by harlem88

- Implements type conversion from all scalar and vector Rust type defined in the `astarte_type` proto file.
- Add tests on AstarteDataType conversion trait.
- Use plural names for repeated fields.

Closes #10.

2022-10-11 10:52 UTC, rbino requested changes

2022-10-11 10:52 UTC, rbino commented on src/types.rs
> +                            }
Is this formatted? I'd expect this closed brace to be two spaces on the left

2022-10-11 10:52 UTC, rbino commented on src/types.rs
> +                astarte_double: value,
This is more of a "retroactive" review, but now that I see the usage I find the fact that, e.g., `AstarteDoubleArray` has a field called that is called `astarte_double` strange.
First, in the [Protobuf Language Guide](https://developers.google.com/protocol-buffers/docs/proto3) repeated fields always use plural names (see e.g. [here](https://developers.google.com/protocol-buffers/docs/proto3): `results`, `snippets`). Second, while using `astarte_x` is useful at the level above to distinguish between the different `oneof` tags, here it's not and I think it introduced unneeded noise.

All in all, I think that all `AstarteSomethingArray` protobufs should just have a `repeated some_type values` field. This makes them more uniform to access, follows the plural name convention and does not introduce unnecessary long names.

2022-10-11 10:52 UTC, rbino commented on src/types.rs
> +    fn from(value: Vec<f64>) -> Self {
On a similar note, I think in Arrays the argument should be called `values` instead of `value`

2022-10-11 10:52 UTC, rbino commented on src/types.rs
> +    fn from(value: Vec<DateTime<Utc>>) -> Self {
The line above says this is not covered by test. Given it's the only non-trivial conversion, I'd add a test for it

2022-10-11 15:07 UTC, rbino approved these changes

2022-10-17 10:04 UTC, FrancescoVaiani approved these changes

2022-10-18 10:37 UTC, bettio approved these changes

2022-10-18 10:38 UTC, merged