feat(config): persist credentials to file
astarte-platform/astarte-message-hub pull request #97
Opened 2023-04-05 16:50 UTC by joshuachp

Add a method to obtain the credentials if not present in the configurations. The credentials are stored in the current working directory or in a directory passed from the command line.

If the credentials are not present, it will try to register the device on Astarte with the pairing token.

Added `tempfile` crate to test using the file system.

Closes #96

2023-04-05 16:52 UTC, joshuachp commented
The credentials and store could also be put in the `config.toml`.

2023-04-13 10:50 UTC, joshuachp commented
This closes also #103

2023-04-18 15:10 UTC, harlem88 requested changes

2023-04-18 16:34 UTC, harlem88 commented on src/config/mod.rs
> +    ) -> Result<&'b str, AstarteMessageHubError> {
Why did you apply this lifetime? Wasn't it easier to return a `String`?

2023-04-19 08:23 UTC, harlem88 approved these changes

2023-04-19 10:04 UTC, sorru94 requested changes

2023-04-19 10:38 UTC, joshuachp commented on src/config/mod.rs
> +        };
Refactored in **8ee5a875b5259483f36a25ec32993da0502124ac**

2023-04-19 14:45 UTC, harlem88 approved these changes

2023-04-19 14:45 UTC, merged